data={
  "Will AI take over the world": {
    "summary": {
      "Headline": "Experts and Business Leaders Discuss the Role of AI in the Workplace",
      "Paragraph": "The articles from CNBC, Forbes, and Harvard Business Review all delve into the impact of artificial intelligence (AI) on businesses and the workforce. While tech experts believe that AI won't replace humans entirely, they emphasize its role in augmenting human capabilities. Forbes encourages companies to embrace AI advancements to stay competitive, while Harvard Business Review stresses the importance of integrating AI into operations to meet evolving customer expectations. Overall, the consensus is that AI will enhance, rather than replace, human intelligence and capabilities.",
      "html": "<table style='border-collapse: collapse; border: 2px solid black;'><tr><th>Article</th><th>Link</th></tr><tr><td>CNBC</td><td><a href='https://www.cnbc.com/2023/12/09/tech-experts-say-ai-wont-replace-humans-any-time-soon.html'>Link</a></td></tr><tr><td>Forbes</td><td><a href='https://www.forbes.com/sites/forbesbooksauthors/2023/07/17/will-ai-take-over-the-world-or-will-you-take-charge-of-your-world/'>Link</a></td></tr><tr><td>Harvard Business Review</td><td><a href='https://hbr.org/2023/08/ai-wont-replace-humans-but-humans-with-ai-will-replace-humans-without-ai'>Link</a></td></tr></table>",
      "media": []
    }
  },
  "Coffee": {
    "summary": {
      "Headline": "Difference between Extractive and Generative Summary",
      "Paragraph": "Extractive text summarization involves extracting important sentences from the original text, while generative text summarization creates new information from scratch. Extractive AI is like a fancy copy-paste machine on steroids, used for tasks like summarizing articles. On the other hand, generative AI acts as a robot writer, generating new stories, poetry, and songs. Each method has its own strengths and applications.",
      "html": "<table>\n       <tr>\n           <th>Extractive vs. Generative Summary</th>\n           <th>Source</th>\n       </tr>\n       <tr>\n           <td>Extractive text summarization extracts important sentences from the original text.</td>\n           <td>(https://nowigence.com/types-of-ai-in-text-summarization-extractive-vs-generative-vs-abstractive/)</td>\n       </tr>\n       <tr>\n           <td>Generative text summarization creates new information from scratch.</td>\n           <td>(https://nowigence.com/extractive-ai-vs-generative-ai/)</td>\n       </tr>\n   </table>",
      "media": []
    }
  },
  "gdp rate year wise for india": {
    "summary": {
      "Headline": "India's GDP Growth and Trends Overview",
      "Paragraph": "India's Gross Domestic Product (GDP) has shown a fluctuating trend over the years, with notable growth rates and changes in GDP per capita. In 2022, India's nominal GDP reached $3,385,090,000,000 USD, with a real GDP of $2,432,020,000,000 USD. The GDP growth rate for 2022 was 7.00%, representing an increase of $193,390,000,000 USD from the previous year. The GDP per capita in India was $2,085 in 2022, showing a 6.3% increase from 2021. The population of India has been steadily increasing, reaching 1,417,173,173 in 2022. India's Gross Domestic Product (GDP) has shown a fluctuating trend over the years, with notable growth rates and changes in GDP per capita. In 2022, India's nominal GDP reached $3,385,090,000,000 USD, with a real GDP of $2,432,020,000,000 USD. The GDP growth rate for 2022 was 7.00%, representing an increase of $193,390,000,000 USD from the previous year. The GDP per capita in India was $2,085 in 2022, showing a 6.3% increase from 2021. The population of India has been steadily increasing, reaching 1,417,173,173 in 2022. The data indicates a positive trajectory for Indias economic development, with efforts needed to sustain and further enhance this growth in the future.",
      "html": "<style> table, th, td { border: 1px solid black; border-collapse: collapse; padding: 5px; text-align: center; } </style>\n      <table>\n        <thead>\n          <tr>\n            <th>Year</th>\n            <th>GDP Nominal (Current USD)</th>\n            <th>GDP Real (Inflation adj.)</th>\n            <th>GDP Change (%)</th>\n            <th>GDP per Capita</th>\n            <th>Population Change (%)</th>\n            <th>Population</th>\n          </tr>\n        </thead>\n        <tbody>\n          <tr>\n            <td>2022</td>\n            <td>$3,385,090,000,000</td>\n            <td>$2,954,980,000,000</td>\n            <td>7.00%</td>\n            <td>$2,085</td>\n            <td>0.68%</td>\n            <td>1,417,173,173</td>\n          </tr>\n          <tr>\n            <td>2021</td>\n            <td>$3,150,310,000,000</td>\n            <td>$2,761,590,000,000</td>\n            <td>9.05%</td>\n            <td>$1,962</td>\n            <td>0.80%</td>\n            <td>1,407,563,842</td>\n          </tr>\n          <tr>\n            <td>2020</td>\n            <td>$2,671,600,000,000</td>\n            <td>$2,532,400,000,000</td>\n            <td>-5.83%</td>\n            <td>$1,814</td>\n            <td>0.96%</td>\n            <td>1,396,387,127</td>\n          </tr>\n          <tr>\n            <td>2019</td>\n            <td>$2,835,610,000,000</td>\n            <td>$2,689,210,000,000</td>\n            <td>3.87%</td>\n            <td>$1,944</td>\n            <td>1.03%</td>\n            <td>1,383,112,050</td>\n          </tr>\n          <tr>\n            <td>2018</td>\n            <td>$2,702,930,000,000</td>\n            <td>$2,588,970,000,000</td>\n            <td>6.45%</td>\n            <td>$1,891</td>\n            <td>1.09%</td>\n            <td>1,369,003,306</td>\n          </tr>\n          <tr>\n            <td>2017</td>\n            <td>$2,651,470,000,000</td>\n            <td>$2,432,020,000,000</td>\n            <td>6.80%</td>\n            <td>$1,796</td>\n            <td>1.16%</td>\n            <td>1,354,195,680</td>\n          </tr>\n          <tr>\n            <td>2016</td>\n            <td>$2,294,800,000,000</td>\n            <td>$2,277,270,000,000</td>\n            <td>8.26%</td>\n            <td>$1,701</td>\n            <td>1.19%</td>\n            <td>1,338,636,340</td>\n          </tr>\n          <tr>\n            <td>2015</td>\n            <td>$2,103,590,000,000</td>\n            <td>$2,103,590,000,000</td>\n            <td>8.00%</td>\n            <td>$1,590</td>\n            <td>1.19%</td>\n            <td>1,322,866,505</td>\n          </tr>\n\n        </tbody>\n        </table>\n",
      "media": []
    }
  },
  "HOW TO BAKE A CAKE": {
    "summary": {
      "Headline": "Instructions on Baking a Cake",
      "Paragraph": "To bake a cake, it's essential to follow step-by-step instructions. Begin by <a href='https://www.crompton.co.in/blogs/kitchen-hacks/baking-cake-in-otg-oven/'>preheating the oven</a> to the recommended temperature. Prepare the cake batter according to your chosen recipe, ensuring it's free of lumps. Grease and flour the baking dish to prevent sticking. Pour the batter into the dish and spread it evenly. Bake in the preheated oven for the specified time, checking for doneness with a toothpick. Allow the cake to cool before removing it from the dish. Finally, <a href='https://recipes.timesofindia.com/recipes/homemade-cake/rs54404412.cms'>decorate the cake</a> according to your preference for a delightful homemade treat",
      "html": "\n<ol>\n  <li>Preheat your oven to the recommended temperature mentioned in your recipe (https://www.crompton.co.in/blogs/kitchen-hacks/baking-cake-in-otg-oven/).</li>\n  <li>Prepare the cake batter according to your recipe, ensuring it's smooth and free of lumps.</li>\n  <li>Grease your baking dish with butter or oil and dust it with flour to prevent sticking.</li>\n  <li>Pour the batter into the prepared dish, spreading it evenly.</li>\n  <li>Bake the cake in the preheated oven for the specified time, checking for doneness with a toothpick or knife (https://www.crompton.co.in/blogs/kitchen-hacks/baking-cake-in-otg-oven/).</li>\n  <li>Allow the cake to cool before removing it from the dish.</li>\n  <li>Decorate your cake as desired, such as with whipping cream and cherries (https://recipes.timesofindia.com/recipes/homemade-cake/rs54404412.cms).</li>\n</ol>\n",
      "media": []
    }
  }
}
